apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

configMapGenerator:
  - name: backend-config
    env: .env

resources:
  - Namespace.yml
  - Service.yml
  - Deployment.yml
