apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql

configMapGenerator:
  - name: mysql-config
    env: .env

resources:
  - Namespace.yml
  - Service.yml
  - StatefulSet.yml
