apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  # Service of type nodeport
  type: NodePort
  # The deafult port for mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32000