apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      restartPolicy: "Always"
      containers:
        - name: mysql
          image: host.minikube.internal:8083/home_management_mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config

          volumeMounts:
            - mountPath: /var/local-mysql
              name: host-path-mysql
      volumes:
        - name: host-path-mysql
          hostPath:
            path: /Users/shacharovadia/Desktop/home_management/k8s/mysql
            type: DirectoryOrCreate